FROM golang:alpine AS builder

WORKDIR /go/src/app
COPY main.go .

# static build
ENV CGO_ENABLED=0
RUN go build -o webserver .

FROM scratch
WORKDIR /app
COPY --from=builder /go/src/app/ /app/

ENTRYPOINT ["./webserver"]
