name: Push Image
on:
  repository_dispatch:
    types: [build-completed]

jobs:
  push-image:
    name: push
    runs-on: ubuntu-latest

    steps:
    - name: checkout HEAD
      uses: actions/checkout@v3

    - name: push docker image
      run: |
        echo "test"

