name: Push Image
on:
  repository_dispatch:
    types: [build-completed]

jobs:
  push-image:
    name: push
    runs-on: ubuntu-latest

    steps:
    - name: checkout HEAD
      uses: actions/checkout@v3

    - name: push docker image
      run: |
        echo "test"
        echo "push target: \"${{ github.event.client_payload.push_target }}\""

    - name: debug
      run: |
        echo "debug"

    - name: Create Events Dataflow Flex Template Json
      if: github.event.client_payload.push_target == '//events/dataflow:image.push'
      run: |
        echo "$TEMPLATE_PATH_PREFIX-${{ github.event.client_payload.source_sha }}.json" 
        echo "$TEMPLATE_IMAGE:${{ github.event.client_payload.source_sha }}"
       env:
         TEMPLATE_IMAGE: "gcr.io/fintech-solutions/events/dataflow:"
         TEMPLATE_PATH_PREFIX: "gs://dataflow-templates/flex-templates/events/dataflow/pubsub-streaming"
