name: wait workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout HEAD
      uses: actions/checkout@v3

    - name: Wait for MockPush to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: master
        check-name: MockPush
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 20

    - name: list env vars
      run: |
        echo "env"
        env
